modLoader = "javafml"
loaderVersion = "[$loaderVersion,)"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/MEGACells/issues"
displayURL = "https://github.com/62832/MEGACells"

[[mods]]
modId = "megacells"
version = "$version"
displayName = "MEGA Cells"
logoFile = "logo.png"
credits = "s/o to the AE2 dev team and the AE2 Discord server for making this all possible."
authors = "90"
description = "ME Greater Accumulation Cells - For when kilobytes just won't do."

[[dependencies.megacells]]
    modId = "ae2"
    mandatory = true
    versionRange = "[$ae2Version,$ae2VersionEnd)"
    ordering = "AFTER"
    side=  "BOTH"

[[dependencies.megacells]]
    modId = "appmek"
    mandatory = false
    versionRange = "[$appmekVersion]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.megacells]]
    modId = "ae2wtlib"
    mandatory = false
    versionRange = "[$ae2wtVersion,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.megacells]]
    modId="appbot"
    mandatory=false
    versionRange = "[$appbotVersion]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.megacells]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[$minecraftVersion]"
    ordering = "NONE"
    side = "BOTH"
